#.github/workflows/INT_Sync.yml
name: INT sync project
on: 
  pull_request:
      branches: [Integration]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Create pull request from INT to MDM project
      run: run: gh pr create -B MDM_Dev -H Integration --title 'Merge Integration into MDM_Dev' --body 'Created by Github action'

    - name: Create pull request from INT to Maps project
      run: run: gh pr create -B Maps_Dev -H Integration --title 'Merge Integration into Maps_Dev' --body 'Created by Github action'
