#.github/workflows/Master_Sync.yml
name: Master sync 
on: 
  push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Create pull request from bugfix/hotfix to portal project
      run: gh pr create -B Portal_Dev -H main --title 'Merge hotfix/bugfix into Portal_Dev' --body 'Created by Github action'

    - name: Create pull request from bugfix/hotfix to MDM project
      run: gh pr create -B MDM_Dev -H main --title 'Merge hotfix/bugfix into MDM_Dev' --body 'Created by Github action'

    - name: Create pull request from bugfix/hotfix to Maps project
      run: gh pr create -B Maps_Dev -H main --title 'Merge hotfix/bugfix into Maps_Dev' --body 'Created by Github action'
