#.github/workflows/Portal_Dev.yml
name: Pull Request Validate
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate sandbox
      run: |
        node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ${{ secrets.PORTALVALI_URL }} -s -a PortalVali

    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app -u PortalVali -c -t

    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human

